@startuml
!theme vibrant
skinparam classAttributeIconSize 0
left to right direction

class MortgageCalculator {
	{method}  {static} +main ( paramString;1 : [Ljava.lang.String; ) : void
}


'class PlantUmlConfigBuilder {
'	{method}  {static} -createClassDiagram ( paramString1 : String ) : java.util.Optional
'	{method}  {static} -createSequenceDiagram ( paramClass1 : Class , paramString2 : String ) : java.util.Optional
'	{method}  {static} +main ( paramString;1 : [Ljava.lang.String; ) : void
'	{method}  {static} -saveToFile ( paramOptional1 : java.util.Optional , paramString2 : String ) : void
'	{method}  {static} -writeToFile ( paramString1 : String , paramString2 : String ) : void
'}


class model.FormattingValues {
}


class model.OverpaymentData {
}


enum model.OverpaymentType {
	{field} +REDUCE_DURATION
	{field} +REDUCE_RATE
}


enum model.RateType {
	{field} +CONSTANT
	{field} +DECREASING
}


class model.Summary {
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +getInterestSumDisplay () : java.math.BigDecimal
	{method} +getOverpaymentProvisionSumDisplay () : java.math.BigDecimal
	{method} +getTotalLossDisplay () : java.math.BigDecimal
	{method} +hashCode () : int
	{method} +toString () : String
}


class model.exception.MortgageException {
}


class model.rate.MortgageResidual {
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +getResidualAmountDisplay () : java.math.BigDecimal
	{method} +getResidualDurationDisplay () : java.math.BigDecimal
	{method} +hashCode () : int
	{method} +toString () : String
}


class model.rate.Rate {
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class model.rate.RateAmounts {
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +getCapitalAmountDisplay () : java.math.BigDecimal
	{method} +getInterestAmountDisplay () : java.math.BigDecimal
	{method} +getRateAmountDisplay () : java.math.BigDecimal
	{method} +hashCode () : int
	{method} +toString () : String
}


class model.rate.TimePoint {
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class MortgageCalculationService {
	{method} +calculate ( paramInputData1 : input.InputData ) : void
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


interface MortgageCalculationServiceI {
	{method}  {abstract} +calculate ( paramInputData1 : input.InputData ) : void
}


class SummaryCalculationService {
	{method} +calculate ( paramList1 : java.util.List , paramInputData2 : input.InputData ) : model.Summary
	{method}  {static} -calculateOverpaymentProvisionSum ( paramInputData1 : input.InputData ) : java.math.BigDecimal
	{method}  {static} -calculateSum ( paramList1 : java.util.List , paramFunction2 : java.util.function.Function ) : java.math.BigDecimal
	{method}  {static} -calculateTotalLoss ( paramBigDecimal1 : java.math.BigDecimal , paramBigDecimal2 : java.math.BigDecimal ) : java.math.BigDecimal
}


interface SummaryCalculationServiceI {
	{method}  {abstract} +calculate ( paramList1 : java.util.List , paramInputData2 : input.InputData ) : model.Summary
}


class input.InputData {
	{method}  {static} +builder () : input.InputData$InputDataBuilder
	{method}  {static} +defaultInputData () : input.InputData
	{method}  {static} +empty () : input.InputData
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +getInterestDisplay () : java.math.BigDecimal
	{method} +getOverpaymentAmount ( paramBigDecimal1 : java.math.BigDecimal ) : java.math.BigDecimal
	{method} +getOverpaymentType ( paramBigDecimal1 : java.math.BigDecimal ) : model.OverpaymentType
	{method} +hashCode () : int
	{method} +toString () : String
	{method} +withInterestPercent ( paramBigDecimal1 : java.math.BigDecimal ) : input.InputData
	{method} +withOverpaymentMap ( paramMap1 : java.util.Map ) : input.InputData
	{method} +withOverpaymentProvisionMonths ( paramBigDecimal1 : java.math.BigDecimal ) : input.InputData
	{method} +withOverpaymentProvisionPercent ( paramBigDecimal1 : java.math.BigDecimal ) : input.InputData
	{method} +withRateType ( paramRateType1 : model.RateType ) : input.InputData
	{method} +withRepaymentStartDate ( paramLocalDate1 : java.time.LocalDate ) : input.InputData
	{method} +withStartingAmount ( paramBigDecimal1 : java.math.BigDecimal ) : input.InputData
	{method} +withStartingDuration ( paramBigDecimal1 : java.math.BigDecimal ) : input.InputData
}


class input.InputData$InputDataBuilder {
	{method} +build () : input.InputData
	{method} +interestPercent ( paramBigDecimal1 : java.math.BigDecimal ) : input.InputData$InputDataBuilder
	{method} +overpaymentMap ( paramMap1 : java.util.Map ) : input.InputData$InputDataBuilder
	{method} +overpaymentProvisionMonths ( paramBigDecimal1 : java.math.BigDecimal ) : input.InputData$InputDataBuilder
	{method} +overpaymentProvisionPercent ( paramBigDecimal1 : java.math.BigDecimal ) : input.InputData$InputDataBuilder
	{method} +rateType ( paramRateType1 : model.RateType ) : input.InputData$InputDataBuilder
	{method} +reference ( paramReference1 : rateCalculation.Reference ) : input.InputData$InputDataBuilder
	{method} +repaymentStartDate ( paramLocalDate1 : java.time.LocalDate ) : input.InputData$InputDataBuilder
	{method} +startingAmount ( paramBigDecimal1 : java.math.BigDecimal ) : input.InputData$InputDataBuilder
	{method} +startingDuration ( paramBigDecimal1 : java.math.BigDecimal ) : input.InputData$InputDataBuilder
	{method} +toString () : String
}


class input.InputData$Scales {
}


class input.InputFromBuilder {
	{method} +load () : input.InputData
}


class input.InputFromFile {
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +load () : input.InputData
	{method}  {static} -mapOverpaymentMap ( paramString1 : String ) : java.util.Map
	{method}  {static} +read () : input.InputData
	{method} +toString () : String
}


class input.InputServiceFactory {
	{method}  {static} +get ( paramInputServiceFactory$InputForm1 : input.InputServiceFactory$InputForm ) : input.InputServiceI
}


enum input.InputServiceFactory$InputForm {
	{field} +BUILDER
	{field} +FILE
}


interface input.InputServiceI {
	{method}  {abstract} +load () : input.InputData
}


class output.OutputServiceFactory {
	{method}  {static} +get ( paramOutputServiceFactory$OutputTo1 : output.OutputServiceFactory$OutputTo ) : output.OutputServiceI
}


enum output.OutputServiceFactory$OutputTo {
	{field} +CONSOLE
	{field} +FILE
	{field} +LOG
}


interface output.OutputServiceI {
	{method}  {abstract} +save ( paramString1 : String ) : void
}


class output.OutputToConsole {
	{method} +save ( paramString1 : String ) : void
}


class output.OutputToFile {
	{method} +save ( paramString1 : String ) : void
}


class output.OutputToLog {
	{method} +save ( paramString1 : String ) : void
}


class printingService.ColumnFormattingService {
	{method}  {static} +builder () : printingService.ColumnFormattingService$ColumnFormattingServiceBuilder
	{method} +getColumnFormat ( paramFormat1 : printingService.Format ) : printingService.Format
	{method} +getColumnFormatInLine ( paramFormat;1 : [LprintingService.Format; ) : printingService.Format
	{method} +getColumnFormatInTurns ( paramFormat;1 : [LprintingService.Format; ) : printingService.Format
	{method} +getEntryFormat ( paramFormat1 : printingService.Format , paramFormat2 : printingService.Format ) : printingService.Format
}


class printingService.ColumnFormattingService$ColumnFormattingServiceBuilder {
	{method} +build () : printingService.ColumnFormattingService
	{method} +toString () : String
}


class printingService.Format {
	{method} +getAsArray () : [Ljava.lang.String;
	{method} +getAsList () : java.util.List
	{method} +getValue ( paramint1 : int ) : String
	{method} +size () : int
}


interface printingService.FormattingFunction {
	{method}  {abstract} +apply ( paramObject1 : Object ) : Object
}


class printingService.FormattingUtils {
	{method} +descriptorCreator ( paramFunction1 : java.util.function.Function , paramInteger2 : Integer ) : java.util.Collection
	{method}  {static} +functionsToObjects ( paramList1 : java.util.List , paramObject2 : Object ) : java.util.List
	{method}  {static} +validateFormatLength ( paramFormat;1 : [LprintingService.Format; ) : int
}


class printingService.PrintingService {
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} -getOverpaymentRow ( paramOverpaymentData1 : model.OverpaymentData , paramFormat2 : printingService.Format ) : StringBuilder
	{method} -getRateRow ( paramFormat1 : printingService.Format , paramRate2 : model.rate.Rate ) : StringBuilder
	{method} +hashCode () : int
	{method} +printData ( paramInputData1 : input.InputData , paramList2 : java.util.List , paramSummary3 : model.Summary ) : void
	{method} +printIntro ( paramInputData1 : input.InputData ) : void
	{method} +printOverpaymentMap ( paramInputData1 : input.InputData , paramFormat2 : printingService.Format ) : void
	{method} +printRates ( paramList1 : java.util.List , paramInputData2 : input.InputData , paramFormat3 : printingService.Format , paramFormat4 : printingService.Format ) : void
	{method} +printSummary ( paramSummary1 : model.Summary ) : void
	{method} -saveMessage ( paramString1 : String ) : void
	{method} -saveMessage ( paramStringBuilder1 : StringBuilder ) : void
	{method} +toString () : String
}


interface printingService.PrintingServiceI {
	{method}  {static} -createSeparator ( paramchar1 : char , paramint2 : int ) : String
	{method}  {abstract} +printData ( paramInputData1 : input.InputData , paramList2 : java.util.List , paramSummary3 : model.Summary ) : void
	{method}  {abstract} +printIntro ( paramInputData1 : input.InputData ) : void
	{method}  {abstract} +printOverpaymentMap ( paramInputData1 : input.InputData , paramFormat2 : printingService.Format ) : void
	{method}  {abstract} +printRates ( paramList1 : java.util.List , paramInputData2 : input.InputData , paramFormat3 : printingService.Format , paramFormat4 : printingService.Format ) : void
	{method}  {abstract} +printSummary ( paramSummary1 : model.Summary ) : void
}


class printingService.RowFormattingService {
	{method} +getKeyValueFormattedRow ( paramFormat1 : printingService.Format , paramList2 : java.util.List , paramObject3 : Object , paramList4 : java.util.List ) : StringBuilder
	{method} +getMultiCollectionFormattedRow ( paramFormat1 : printingService.Format , paramint2 : int , paramList;3 : [Ljava.util.List; ) : StringBuilder
	{method} +getValueFormattedRow ( paramFormat1 : printingService.Format , paramObject2 : Object , paramList3 : java.util.List ) : StringBuilder
}


class printingService.SizeFormattingService {
	{method}  {static} +builder () : printingService.SizeFormattingService$SizeFormattingServiceBuilder
	{method} -calculateMaxColumnSize ( paramCollection1 : java.util.Collection , paramCollection2 : java.util.Collection ) : [Ljava.lang.Integer;
	{method} -createStringsForFormatting ( paramInteger;1 : [Ljava.lang.Integer; ) : [Ljava.lang.String;
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +getFormats ( paramCollection1 : java.util.Collection ) : printingService.Format
	{method} +getFormats ( paramObject1 : Object , paramCollection2 : java.util.Collection ) : printingService.Format
	{method} +getFormats ( paramCollection1 : java.util.Collection , paramCollection2 : java.util.Collection ) : printingService.Format
	{method} +hashCode () : int
	{method} +toString () : String
	{method} +valuesToDescribersFormat ( paramCollection1 : java.util.Collection ) : printingService.Format
}


class printingService.SizeFormattingService$SizeFormattingServiceBuilder {
	{method} +build () : printingService.SizeFormattingService
	{method} +toString () : String
}


class printingService.TableFormattingService {
	{method} +KeyValueFormatter ( paramCollection1 : java.util.Collection , paramCollection2 : java.util.Collection , paramCollection3 : java.util.Collection ) : printingService.Format
	{method} +collectionFormatter ( paramCollection1 : java.util.Collection , paramList2 : java.util.List ) : printingService.Format
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +multiCollectionFormatter ( paramCollection;1 : [Ljava.util.Collection; ) : printingService.Format
	{method} +toString () : String
}


interface printingService.TableFormattingServiceI {
	{method}  {abstract} +constantKey_ValueFormatter ( paramCollection1 : java.util.Collection , paramCollection2 : java.util.Collection , paramCollection3 : java.util.Collection ) : [Ljava.lang.String;
	{method}  {abstract} +formatKey_ValueRow ( paramObject1 : Object , paramString;2 : [Ljava.lang.String; , paramCollection3 : java.util.Collection , paramCollection4 : java.util.Collection ) : StringBuilder
	{method}  {abstract} +formatValueRow ( paramObject1 : Object , paramString;2 : [Ljava.lang.String; , paramCollection3 : java.util.Collection ) : StringBuilder
	{method}  {abstract} +key_valueFormatter ( paramCollection1 : java.util.Collection , paramCollection2 : java.util.Collection , paramCollection3 : java.util.Collection , paramCollection4 : java.util.Collection ) : [Ljava.lang.String;
	{method}  {abstract} +valueFormatter ( paramCollection1 : java.util.Collection , paramCollection2 : java.util.Collection ) : [Ljava.lang.String;
}


class rateCalculation.AmountsCalculationService {
	{method} +calculate ( paramInputData1 : input.InputData , paramMortgageResidual2 : model.rate.MortgageResidual ) : model.rate.RateAmounts
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


interface rateCalculation.AmountsCalculationServiceI {
	{method}  {abstract} +calculate ( paramInputData1 : input.InputData , paramMortgageResidual2 : model.rate.MortgageResidual ) : model.rate.RateAmounts
	{method}  {static} +calculateInterestAmount ( paramBigDecimal1 : java.math.BigDecimal , paramBigDecimal2 : java.math.BigDecimal ) : java.math.BigDecimal
	{method}  {static} +calculateMortgageConstant ( paramBigDecimal1 : java.math.BigDecimal ) : java.math.BigDecimal
}


class rateCalculation.ConstantAmountsCalculationService {
	{method} +calculate ( paramInputData1 : input.InputData , paramBigDecimal2 : java.math.BigDecimal ) : model.rate.RateAmounts
	{method} -calculateCapitalAmount ( paramBigDecimal1 : java.math.BigDecimal , paramBigDecimal2 : java.math.BigDecimal , paramBigDecimal3 : java.math.BigDecimal ) : java.math.BigDecimal
	{method} -calculateRateAmount ( paramBigDecimal1 : java.math.BigDecimal , paramBigDecimal2 : java.math.BigDecimal , paramBigDecimal3 : java.math.BigDecimal , paramBigDecimal4 : java.math.BigDecimal , paramBigDecimal5 : java.math.BigDecimal ) : java.math.BigDecimal
	{method} -compareWithResidual ( paramBigDecimal1 : java.math.BigDecimal , paramBigDecimal2 : java.math.BigDecimal , paramBigDecimal3 : java.math.BigDecimal ) : java.math.BigDecimal
}


interface rateCalculation.ConstantAmountsCalculationServiceI {
	{method}  {abstract} +calculate ( paramInputData1 : input.InputData , paramBigDecimal2 : java.math.BigDecimal ) : model.rate.RateAmounts
}


class rateCalculation.DecreasingAmountsCalculationService {
	{method} +calculate ( paramInputData1 : input.InputData , paramBigDecimal2 : java.math.BigDecimal ) : model.rate.RateAmounts
	{method} -calculateCapitalAmount ( paramBigDecimal1 : java.math.BigDecimal , paramBigDecimal2 : java.math.BigDecimal , paramBigDecimal3 : java.math.BigDecimal ) : java.math.BigDecimal
	{method} -calculateRateAmount ( paramBigDecimal1 : java.math.BigDecimal , paramBigDecimal2 : java.math.BigDecimal ) : java.math.BigDecimal
}


interface rateCalculation.DecreasingAmountsCalculationServiceI {
	{method}  {abstract} +calculate ( paramInputData1 : input.InputData , paramBigDecimal2 : java.math.BigDecimal ) : model.rate.RateAmounts
}


class rateCalculation.RateCalculationService {
	{method} +calculate ( paramInputData1 : input.InputData ) : java.util.List
	{method} -calculateRate ( paramBigDecimal1 : java.math.BigDecimal , paramInputData2 : input.InputData , paramRate3 : model.rate.Rate ) : model.rate.Rate
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} -getZeroRate ( paramInputData1 : input.InputData ) : model.rate.Rate
	{method} +hashCode () : int
	{method} +toString () : String
}


interface rateCalculation.RateCalculationServiceI {
	{method}  {abstract} +calculate ( paramInputData1 : input.InputData ) : java.util.List
}


class rateCalculation.Reference {
}


class rateCalculation.ResidualCalculationService {
	{method} +calculate ( paramInputData1 : input.InputData , paramTimePoint2 : model.rate.TimePoint , paramRateAmounts3 : model.rate.RateAmounts , paramMortgageResidual4 : model.rate.MortgageResidual ) : model.rate.MortgageResidual
	{method} -calculateResidualAmount ( paramRateAmounts1 : model.rate.RateAmounts , paramBigDecimal2 : java.math.BigDecimal ) : java.math.BigDecimal
	{method} -calculateResidualOverpaymentAmount ( paramInputData1 : input.InputData , paramBigDecimal2 : java.math.BigDecimal , paramBigDecimal3 : java.math.BigDecimal ) : java.math.BigDecimal
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} -getOverpaymentMortgageResidual ( paramInputData1 : input.InputData , paramTimePoint2 : model.rate.TimePoint , paramRateAmounts3 : model.rate.RateAmounts , paramBigDecimal4 : java.math.BigDecimal , paramBigDecimal5 : java.math.BigDecimal ) : model.rate.MortgageResidual
	{method} +hashCode () : int
	{method} +reduceDurationByOne ( paramBigDecimal1 : java.math.BigDecimal ) : java.math.BigDecimal
	{method} -reduceDurationOfConstant ( paramInputData1 : input.InputData , paramRateAmounts2 : model.rate.RateAmounts , paramBigDecimal3 : java.math.BigDecimal ) : java.math.BigDecimal
	{method} -reduceDurationOfDecreasing ( paramRateAmounts1 : model.rate.RateAmounts , paramBigDecimal2 : java.math.BigDecimal ) : java.math.BigDecimal
	{method} +toString () : String
	{method} -updateOverpaymentCut ( paramInputData1 : input.InputData , paramBigDecimal2 : java.math.BigDecimal , paramBigDecimal3 : java.math.BigDecimal ) : void
	{method} -updateReferenceAmount ( paramInputData1 : input.InputData , paramBigDecimal2 : java.math.BigDecimal ) : void
	{method} -updateReferenceDuration ( paramInputData1 : input.InputData , paramBigDecimal2 : java.math.BigDecimal ) : void
}


interface rateCalculation.ResidualCalculationServiceI {
	{method}  {abstract} +calculate ( paramInputData1 : input.InputData , paramTimePoint2 : model.rate.TimePoint , paramRateAmounts3 : model.rate.RateAmounts , paramMortgageResidual4 : model.rate.MortgageResidual ) : model.rate.MortgageResidual
}


class rateCalculation.TimePointService {
	{method} +calculate ( paramBigDecimal1 : java.math.BigDecimal , paramInputData2 : input.InputData ) : model.rate.TimePoint
	{method} -calculateDate ( paramBigDecimal1 : java.math.BigDecimal , paramInputData2 : input.InputData ) : java.time.LocalDate
	{method} -calculateMonth ( paramBigDecimal1 : java.math.BigDecimal ) : java.math.BigDecimal
	{method} -calculateOverpayment ( paramBigDecimal1 : java.math.BigDecimal , paramInputData2 : input.InputData ) : Boolean
	{method} -calculateYear ( paramBigDecimal1 : java.math.BigDecimal ) : java.math.BigDecimal
}


interface rateCalculation.TimePointServiceI {
	{method}  {abstract} +calculate ( paramBigDecimal1 : java.math.BigDecimal , paramInputData2 : input.InputData ) : model.rate.TimePoint
}


'input -[hidden]-> printingService
'output -[hidden]r-> input


MortgageCalculator --d>  MortgageCalculationServiceI : instance
'model.FormattingValues "1" o-- "0..*"  printingService.FormattingFunction : introDescriptors
'model.FormattingValues "1" o-- "0..*"  printingService.FormattingFunction : overpaymentDescribers
'model.FormattingValues "1" o-- "0..*"  printingService.FormattingFunction : rateDescribers
'model.FormattingValues "1" o-- "0..*"  printingService.FormattingFunction : summaryDescriptors
'model.FormattingValues *--  printingService.FormattingFunction : DEFAULT_DESCRIBER

'model.OverpaymentData *--  model.OverpaymentType : overpaymentType
'model.rate.Rate *--  model.rate.MortgageResidual : mortgageResidual
'model.rate.Rate *--  model.rate.RateAmounts : rateAmounts
'model.rate.Rate *--  model.rate.TimePoint : timePoint

MortgageCalculationService ..u|>  MortgageCalculationServiceI
MortgageCalculationService *--d  rateCalculation.RateCalculationServiceI : rateCalculationServiceI
MortgageCalculationService *--d  SummaryCalculationServiceI : summaryCalculationServiceI
MortgageCalculationService *--d  printingService.PrintingServiceI : printingServiceI

SummaryCalculationService ..u|>  SummaryCalculationServiceI

'input -[hidden]-> rateCalculation
model -[hidden]-> input

input.InputData "1" o-- "0..*"  model.OverpaymentData : overpaymentMap
input.InputData *--  model.RateType : rateType
input.InputData *--  rateCalculation.Reference : reference
'input.InputData$InputDataBuilder "1" o-- "0..*"  model.OverpaymentData : overpaymentMap
'input.InputData$InputDataBuilder -->  model.RateType : rateType
'input.InputData$InputDataBuilder -->  rateCalculation.Reference : reference
input.InputFromBuilder ..|>  input.InputServiceI
input.InputFromFile ..|>  input.InputServiceI

output.OutputToConsole ..u|>  output.OutputServiceI
output.OutputToFile ..u|>  output.OutputServiceI
output.OutputToLog ..u|>  output.OutputServiceI
printingService.PrintingService *--  output.OutputServiceI : outputServiceI
printingService.PrintingService *--  printingService.TableFormattingService : tableFormatter
printingService.PrintingService ..|>  printingService.PrintingServiceI
printingService.TableFormattingService *--  printingService.ColumnFormattingService : columnFormattingService
printingService.TableFormattingService *--  printingService.RowFormattingService : rowFormattingService
printingService.TableFormattingService *--  printingService.SizeFormattingService : formatter
rateCalculation.AmountsCalculationService *--  rateCalculation.ConstantAmountsCalculationService : constantAmountsCalculationService
rateCalculation.AmountsCalculationService *--  rateCalculation.DecreasingAmountsCalculationService : decreasingAmountsCalculationService
rateCalculation.AmountsCalculationService ..|>  rateCalculation.AmountsCalculationServiceI
rateCalculation.ConstantAmountsCalculationService ..|>  rateCalculation.ConstantAmountsCalculationServiceI
rateCalculation.DecreasingAmountsCalculationService ..|>  rateCalculation.DecreasingAmountsCalculationServiceI
rateCalculation.RateCalculationService *--  rateCalculation.AmountsCalculationServiceI : amountsCalculationServiceI
rateCalculation.RateCalculationService *--  rateCalculation.ResidualCalculationServiceI : residualCalculationServiceI
rateCalculation.RateCalculationService *--  rateCalculation.TimePointServiceI : timePointServiceI
rateCalculation.RateCalculationService ..|>  rateCalculation.RateCalculationServiceI
rateCalculation.ResidualCalculationService ..|>  rateCalculation.ResidualCalculationServiceI
rateCalculation.TimePointService ..|>  rateCalculation.TimePointServiceI

hide methods

@enduml