SELECT * FROM OPINIONS;
SELECT * FROM information_schema.tables;

ALTER TABLE CUSTOMER
RENAME TO CUSTOMERS;
ALTER TABLE OPINION
RENAME TO OPINIONS;
ALTER TABLE PRODUCT
RENAME TO PRODUCTS;
ALTER TABLE PRODUCER
RENAME TO PRODUCERS;
ALTER TABLE PURCHASE
RENAME TO PURCHASES;

-- 4.
SELECT * FROM OPINION WHERE STARS < 4;

-- 5.
SELECT DATE_OF_PURCHASE, PRODUCT_ID, PRODUCT_CODE 
	FROM PURCHASES AS PUR
	INNER JOIN PRODUCTS PRO ON PUR.PRODUCT_ID = PRO.ID
WHERE DATE_TRUNC('day', DATE_OF_PURCHASE) < '2023-06-01'::timestamp;

SELECT DISTINCT PRODUCT_CODE 
	FROM PURCHASES AS PUR
	INNER JOIN PRODUCTS PRO ON PUR.PRODUCT_ID = PRO.ID
WHERE DATE_OF_PURCHASE < '2023-06-01'
ORDER BY PRODUCT_CODE;

-- 6.
SELECT 
	COUNT(PRODUCT_CODE) AS COU,
-- 	string_agg(DISTINCT PRODUCT_CODE, ',')
	PRODUCT_CODE
FROM PURCHASES AS PUR
	INNER JOIN PRODUCTS PRO ON PUR.PRODUCT_ID = PRO.ID
		GROUP BY PRODUCT_CODE
		ORDER BY COU DESC
	LIMIT 5;

-- 7.
SELECT DISTINCT CUSTOMER_ID, CUST.NAME, CU  ST.SURNAME ADULTS_ONLY FROM PURCHASES AS PUR
INNER JOIN PRODUCTS PRO ON PUR.PRODUCT_ID = PRO.ID
INNER JOIN CUSTOMER CUS ON PUR.CUSTOMER_ID = CUST.ID
WHERE ADULTS_ONLY IS TRUE 
ORDER BY CUSTOMER_ID;

-- 8.
-- i picked acaig2e and abentje1s
SELECT * FROM PRODUCERS ORDER BY PRODUCER_NAME;
SELECT PRODUCT_PRICE, PRODUCER_NAME FROM PRODUCTS 
INNER JOIN PRODUCERS ON PRODUCTS.PRODUCER_ID = PRODUCERS.ID
WHERE PRODUCER_NAME = 'abentje1s';

UPDATE PRODUCTS SET PRODUCT_PRICE = 40
FROM PRODUCERS
WHERE PRODUCER_ID = PRODUCERS.ID AND PRODUCER_NAME = 'abentje1s' 
AND PRODUCT_PRICE > 50;

UPDATE PRODUCTS SET PRODUCT_PRICE = 40
WHERE PRODUCER_ID IN (SELECT ID FROM PRODUCER WHERE PRODUCER_NAME = 'abentje1s') 
AND PRODUCT_PRICE > 50;

9.
SELECT CUSTOMER_ID, USER_NAME, COUNT(STARS) FROM OPINIONS
INNER JOIN CUSTOMERS ON CUSTOMER_ID = CUSTOMERS.ID
WHERE STARS = 5
GROUP BY CUSTOMER_ID, USER_NAME;

-- 10.
SELECT PRODUCER_NAME, COUNT(PRODUCTS.ID) AS COU FROM PRODUCTS
INNER JOIN PRODUCERS ON PRODUCER_ID = PRODUCERS.ID
GROUP BY PRODUCER_NAME
ORDER BY COU DESC, PRODUCER_NAME ASC;
LIMIT 1

SELECT 
	PRODUCERS.PRODUCER_NAME,
	SUM(QUANTITY) AS SU
FROM PURCHASES
    INNER JOIN PRODUCTS ON PRODUCT_ID = PRODUCTS.ID
    INNER JOIN PRODUCERS ON PRODUCER_ID = PRODUCERS.ID
GROUP BY PRODUCERS.PRODUCER_NAME
ORDER BY SU DESC
LIMIT 1;

-- 11.
SELECT PRODUCTS.ID, PRODUCT_PRICE FROM PRODUCTS
ORDER BY PRODUCT_PRICE DESC
OFFSET 1
LIMIT 1;

-- 12.
SELECT PRODUCT_NAME, PRODUCT_ID, COUNT(PRODUCT_ID) AS COU FROM OPINIONS
    INNER JOIN PRODUCTS ON PRODUCT_ID = PRODUCTS.ID
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY COU DESC
LIMIT 10;

13.
SELECT 
	DATE_TRUNC('month', DATE_OF_PURCHASE) AS DATE_OF, 
	SUM(QUANTITY * PRODUCTS.PRODUCT_PRICE)
FROM PURCHASES
	INNER JOIN PRODUCTS ON PRODUCT_ID = PRODUCTS.ID
GROUP BY DATE_OF
ORDER BY DATE_OF DESC;


13.official
WITH TMP AS (
	SELECT
		DATE_TRUNC('month', pur.date_time) AS DATE_TIME,
		pur.quantity,
		pr.product_price,
		pur.quantity * pr.product_price AS INCOME_PER_PRODUCT
	FROM purchase pur
		inner join product pr on pr.id = pur.product_id
	order by DATE_TIME, INCOME_PER_PRODUCT
)
SELECT TMP.DATE_TIME, SUM(TMP.INCOME_PER_PRODUCT) AS INCOME
	FROM TMP
GROUP BY TMP.DATE_TIME
ORDER BY TMP.DATE_TIME;