
-- DDL - Data definition Language - Komendy do tworzenia tabel


CREATE TABLE EMPLOYEES(
        ID	 		INT 			NOT NULL,
        NAME		VARCHAR(20) 	NOT NULL,
SURNAME 	VARCHAR(20) 	NOT NULL,
AGE 		SMALLINT,
SALARY 		NUMERIC(7,2) 	NOT NULL,
DATE_OF_EMPLOYMENT DATE,
PRIMARY KEY(ID)

SELECT * FROM information_schema.columns
WHERE table_name = 'employees';

ALTER TABLE EMPLOYEES
ALTER COLUMNS SURNAME DROP NOT NULL;

INSERT INTO EMPLOYEES (ID, NAME, SURNAME, AGE, SALARY, DATE_OF_EMPLOYMENT)
VALUES (1, 'ALEX', 'KOCIARZ', 43, 7689.3, '2012-01-01'),
(3,'A','K',4,3,'1-1-1')

DELETE * FROM EMPLOYEES;


SELECT * FROM EMPLOYEES;

SELECT ID, NAME, AGE FROM EMPLOYEES;

SELECT
ID AS PKEY,
NAME AS my_name
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE name = 'ALEX'
AND age = '52' -- OR

        SELECT
NAME,
AGE,
AGE % 10 AS AGE_MOD
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE AGE IS NOT NULL AND
AGE NOT IN (3, 2, 70) AND
NAME LIKE '%RO%'; -- % AS * String.contains()

        -- <>, :=
        -- <, >, >=, <=
        -- =

        -- AND, OR, IN (smth), BETWEEN 1 and 3, LIKE

SELECT DISTINCT NAME FROM EMPLOYEES
ORDER BY NAME DESC, SURNAME ASC -- descending ascending
LIMIT 2;

SELECT AGE, COUNT(*), SUM(SALARY),
FROM EMPLOYEES
GROUP BY NAME;

-- GROUP_CONCAT functions to List.
        -- AVG, MAX, MIN,

UPDATE EMPLOYESS
SET SALARY = 1, SURNAME = 'MEOWIN'

-- 	DELETE FROM EMPLOYEES;

